#Creating the multi-component RepliTali estimator for blood
#Will generate estimates of replicative history for both lymhpoid and myeloid blood lineages from whole blood samples

##Step 1: Training the model
library(GEOquery)
library(GenomicRanges)
library(FlowSorted.Blood.EPIC)
library(rtracklayer)
library(glmnet)
library(coefplot)
library(reshape2)
library(ggplot2)


download.file('https://raw.githubusercontent.com/jamieendicott/Blood_RepliTali/main/Training_data.csv?token=GHSAT0AAAAAABWZ3SVAVRG2NII65J2QHLDMYW6UT2A',
              './Training_data.csv') #p-data from GSE167998, trimmed and with fraction of myeloid/lymphoid populations
p<-read.csv('Training_data.csv')

#import processed betas from GSE167998
#very large, will take some time
download.file('https://ftp.ncbi.nlm.nih.gov/geo/series/GSE167nnn/GSE167998/suppl/GSE167998_matrix_processed.txt.gz','./GSE167998_matrix_processed.txt.gz')
g<-read.table('GSE167998_matrix_processed.txt.gz',row.names=1,header=TRUE) #also contains pvals, trim!
g<-g[,c(match(p$base,colnames(g)))]
dim(g)
#[1] 865859     68

#Calculate RepliTali estimates for each sample
download.file('https://raw.githubusercontent.com/jamieendicott/Nature_Comm_2022/main/RepliTali/RepliTali_coefs.csv','./RepliTali_coefs.csv')
RT<-read.csv('RepliTali_coefs.csv')

p.train<-subset(p,p$type=='pure')
x<-g[c(match(RT$Coefficient[-1],rownames(g))),c(match(p.train$base,colnames(g)))]
X<-apply(x,2,function(x) RT$Value[-1]*x)
est.RT<-apply(X,2,function(x) sum(x, na.rm=T) +RT$Value[1])
p.train$RT<-est.RT
#Calculate lineage (M vs L) -specific RepliTali estimate based on cellular fraction                               
p.train$RT_M<-p.train$fraction_myeloid*p.train$RT
p.train$RT_L<-p.train$fraction_lymphoid*p.train$RT              

#Normalize estimates with RepliTali estimate from chronologically young MPPs
#Note: this data is from WGBS! mapped to hg38
download.file('http://ftp.ebi.ac.uk/pub/databases/blueprint/data/homo_sapiens/GRCh38/bone_marrow/F2012-2912/hematopoietic_multipotent_progenitor_cell/Bisulfite-Seq/CNAG/HPC-V151.CPG_methylation_calls.bs_call.GRCh38.20160531.bw',
              './HPC-V151.CPG_methylation_calls.bs_call.GRCh38.20160531.bw')
download.file('http://ftp.ebi.ac.uk/pub/databases/blueprint/data/homo_sapiens/GRCh38/bone_marrow/F2012-2912/hematopoietic_multipotent_progenitor_cell/Bisulfite-Seq/CNAG/G199.CPG_methylation_calls.bs_call.GRCh38.20160531.bw',
              './G199.CPG_methylation_calls.bs_call.GRCh38.20160531.bw')
MPP.1<-import(list.files(pattern = ".bw")[1])
MPP.2<-import(list.files(pattern = ".bw")[2])              
#filter to those on EPIC array
download.file('https://zhouserver.research.chop.edu/InfiniumAnnotation/20180909/EPIC/EPIC.hg38.manifest.tsv.gz','./EPIC.hg38.manifest.tsv.gz')
man<-read.delim('EPIC.hg38.manifest.tsv.gz')
man<-man[,c(1:3,5)]
man<-na.omit(man)
gr.man<-GRanges(seqnames = man$CpG_chrm,
                            ranges = IRanges(start = man$CpG_beg,
                                             end = man$CpG_end))
MPP<-as.data.frame(subsetByOverlaps(MPP.2,gr.man))
X <- split(MPP, MPP$seqnames)
for( i in seq_along(X)){
  X[[i]]$probeID<-man[c(match(X[[i]]$end,man$CpG_end)),4]
} 
X2<-do.call("rbind", X)
#save betas onto g set, but keep in mind they were generated by another method!
g$MPP.2<-X2[c(match(rownames(g),X2$probeID)),6]
#calculate replitali estimates for MPP samples
x<-g[c(match(RT$Coefficient[-1],rownames(g))),69:70] #only a handful of NAs
X<-apply(x,2,function(x) RT$Value[-1]*x)
est.RT<-apply(X,2,function(x) sum(x, na.rm=T) +RT$Value[1])
est.RT
#    MPP.1     MPP.2
#-25.18618 -25.23684
#adjust estimates for purified cell types by 25.2 PDs           
p.train$RT_M_a<-p.train$RT_M+(25.2*p.train$fraction_myeloid)
p.train$RT_L_a<-p.train$RT_L+(25.2*p.train$fraction_lymphoid)
              
##train models for both lymphoid and myeloid lineages to MPP-normalized, estimated PDs
set.seed(12345)
model<-"lymphoid"
betas<-g[,c(match(p.train$base,colnames(g)))] #note: pulls OUT MPPs
x.r<-t(betas)
y.r<-paste(p.train$RT_L_a) #swap to correct lineage for model
y.r<-as.numeric(y.r)
y.r
ELR.r<-glmnet(x.r,y.r,family="gaussian",alpha=0.5)
cv.fit.ELR.r<-cv.glmnet(x.r,y.r,alpha=0.5)
dim(extract.coef(cv.fit.ELR.r,lambda="lambda.1se"))
#[1] 111 myeloid, 222 lymphoid
cvfit.r<-extract.coef(cv.fit.ELR.r,lambda="lambda.1se")
write.csv(cvfit.r,paste0(model,"enetmodel.csv"))
#there is some variability with CpGs and coefficients upon each run (many CpGs behave similarly)
                      
#Test models on all samples in this GSE
cell_type<-"myeloid"
cvfit.r<-read.csv(paste0(cell_type,"enetmodel.csv"))
dim(cvfit.r)
              
betas<-g[,c(match(p$base,colnames(g)))]
x.betas<-subset(betas,rownames(betas)%in%cvfit.r$X)
X<-apply(x.betas,2,function(x) cvfit.r$Value[-1]*x)
r<-apply(X,2,function(x) sum(x, na.rm=T) +cvfit.r$Value[1])
p$r.myeloid<-r

#plot results
p$type<-as.factor(p$type)
p$mem<-p$bmem.ch1+p$cd4mem.ch1
df<-p[,c(3,4,6,7,21:23)]
mdat<-melt(df,id.vars=c('title','type','fraction_myeloid','fraction_lymphoid','mem'))         
g<-ggplot(data=mdat,aes(col=variable,x=title,y=value))
pdf('test.pdf')
g+geom_point()+theme_bw()+geom_hline(yintercept = 0,col="gray")+
         facet_wrap(~type,scales='free_x')
dev.off()         
#compare lymphoid estimate vs memory cell populations
         
         
#train 450K array-based models
download.file('https://zhouserver.research.chop.edu/InfiniumAnnotation/20180909/HM450/HM450.hg38.manifest.tsv.gz','./HM450.hg38.manifest.tsv.gz')
man450k<-read.delim('HM450.hg38.manifest.tsv.gz')
set.seed(12345)
model<-"myeloid"
betas<-g[,c(match(p.train$base,colnames(g)))] #note: pulls OUT MPPs
betas<-subset(betas,rownames(betas)%in%man450k$probeID) #452453
x.r<-t(betas)
y.r<-paste(p.train$RT_M_a) #swap to correct lineage for model
y.r<-as.numeric(y.r)
y.r
ELR.r<-glmnet(x.r,y.r,family="gaussian",alpha=0.5)
cv.fit.ELR.r<-cv.glmnet(x.r,y.r,alpha=0.5)
dim(extract.coef(cv.fit.ELR.r,lambda="lambda.1se"))
#[1] 95 myeloid, 171 lymphoid
cvfit.r<-extract.coef(cv.fit.ELR.r,lambda="lambda.1se")
write.csv(cvfit.r,paste0(model,".450kenetmodel.csv"))
       
         
